baseURL = 'https://hyperfemmelesbian.gay/'
languageCode = 'en-us'
title = 'Hyper Femme Lesbian Gay'
theme = 'sparkles'

[params]
  description = 'Protocols, Protocols, Protocols!'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Protocols'
  pageRef = '/protocols'
  weight = 20

[[menus.main]]
  name = 'Gremium'
  pageRef = '/gremium'
  weight = 25

[[menus.main]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 30
